# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    stdlib:
        repo: "puppetlabs/stdlib"
        ref: "4.25.1"
    docker:
        repo: "puppetlabs/docker"
        ref: "1.1.0"
    augeasproviders_sysctl:
        repo: "herculesteam/augeasproviders_sysctl"
        ref: "2.2.0"
    augeasproviders_core:
        repo: "herculesteam/augeasproviders_core"
        ref: "2.1.4"
    apt:
        repo: "puppetlabs/apt"
        ref: "4.5.1"