.gitignore:
    paths:
        - "/test/integration/**/.librarian"
        - "/test/integration/**/.tmp"
        - ".kitchen"
        - ".vscode"
Gemfile:
    required:
        ":development":
            - gem: "kitchen-azurerm"
              version: "0.14.9"
            - gem: "kitchen-puppet"
              version: "3.5.1"
            - gem: "serverspec"
              version: "2.41.5"
            - gem: "test-kitchen"
              version: "2.2.5"
Rakefile:
    requires:
        - "kitchen/rake_tasks"
    extras:
        - "Kitchen::RakeTasks.new"
        - |
            task :integration_test do
              [:metadata_lint, :lint, :validate, :spec].each do |test|
                Rake::Task[test].invoke
              end
              Rake::Task['kitchen:all'].invoke
            end
.travis.yml:
    user: "dodevops"
    secure: "7jQOQ9TN7/+b2idg52Fo4zRkYRP5exUVSizIJSP2Cs8KqY+I28or9C2XUiFpJslMySEN7+UEgWwqFpFjDW4cwaIO+oqhRWCJ8K2WDea4dx62lyr5ymV+H2p0liGTeyfU1JV5PXwFUTyt/c8+vaVkytxoaPavWssEj9zpHH67Hu3zmBFzDPtPONcFEBxrSvOCsV/UxdhjqFg0ARs7eS32tlQ2VTC8SA+6MBnW9FLaDuY/DiDap7JLYF6Biak1R02LwaYPaX1dSOz0LvU3f36e9MKYVCEPdYhDFmLWDUk3CxY61xatOBiS+FY/gDaFpKgB3o3dDSAL4Z4K75Sqby0uCKhtKh8Y7Am8PZ+hn7++cmeapNQI3hFNvaT4313IAIGhpFb6J6hOmgKNCyOaUtthOVR2ApqgNcftlfBjt1g7SK+eBVLt9M7om3yYzwF+BH/VnJU91Pfr1LMSf2qBj4wG14wc4MHLMrLUQffYGSJjbjF9l0btwBml6oiQpchx1re7fTJYNwM3j8kI2vwZVTg25dEa4ZT2YYuU31kpxpJ5NFMlnmjSlfUZIFS02IqKeDiclb7u4BG6zf66Pn63R6rGd2Yw5DI4jdjFkkODWaRZ7UoKtfRCh4BO4Hlgmqsz0UpGZqbIzJKnyuRyJZ7OZx3M8xdOWoRH8EcCi7/fxhT6gY0="
"spec/default_facts.yml":
    extra_facts:
        docker_home_dirs:
            root: "/docker"
